POST http://localhost:3000/api/v1/user
Content-Type: application/json

{ 
    "name": "Heber Robert",
    "email": "euheber1@gmail.com",
    "tracking_code": "AH18NBHH"
}

###
GET http://localhost:3000/api/v1/user/3a33c5f6-9aa7-423d-b397-b835edd46b8b